
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzenbrbmlgnsrucndama.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZW5icmJtbGduc3J1Y25kYW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDUxOTUsImV4cCI6MjA2MjE4MTE5NX0._mLgRgwUQQ5HunrNbUYND_sEVwoeIVBuWqbNpY-UEwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
